### ISSUE TITLE
dig doesn't work behind a proxy?

### ISSUE THREAD

**Issue by saptarshiguha** [tesseradata/install-emr#14]
On a system with a proxy, the dig command doesn't work. Is this a better substitute?

 curl -s http://whatismijnip.nl |cut -d " " -f 5

**Comment by hafen** [comment]
Yes.  That looks good.  Perhaps a more stable source would be aws?

```
curl -s http://checkip.amazonaws.com/
```

**Comment by saptarshiguha** [comment]
Absolutely.

**Comment by hafen** [comment]
Cool.  I don't see any downside.  I'll modify it directly.
