### ISSUE TITLE
Check for valid cluster start command

### ISSUE THREAD

**Issue by saptarshiguha** [tesseradata/install-emr#15]
Might want to check if the cluster started correctly in
https://github.com/tesseradata/install-emr/blob/master/emr-3.2.1/tessera-emr.sh#L174

E.g. check for CLUSTER_ID non null

if [ -z "$CLUSTER_ID" ]; then
    exit 11
fi

echo "Tagging cluster…"
aws emr add-tags --resource-id $CLUSTER_ID --tags $AWS_RES_TAG_KEY=$AWS_RES_TAG_VALUE

**Comment by hafen** [comment]
Good idea.  Done.
