### ISSUE TITLE
Launched 2 node cluster ; but getting error message

### ISSUE THREAD

**Issue by bhawani14** [tesseradata/install-emr#17]
On the R console of the master node on typing library(Rhipe):

> library(Rhipe)
Loading required package: codetools
Loading required package: rJava
Error : .onLoad failed in loadNamespace() for 'Rhipe', details:
  call: fun(libname, pkgname)
  error: could not find function "handleIOFormats"
In addition: Warning message:
S3 methods ‘[.mapfile’, ‘[<-.mapfile’, ‘[[.mapfile’, ‘[[<-.mapfile’, ‘print.mapfile’ were declared in NAMESPACE but not found 
Error: package or namespace load failed for ‘Rhipe’

I guess all the prerequisite packages have been packaged ...Or I have to install them ?

**Comment by bhawani14** [comment]
This is not an issue ..I am sorry to have posted..
One has to simply load these packages in the R console...

**Comment by hafen** [comment]
No problem.  Actually, all the packages should be installed once it's up and running, so there is probably something going wrong in the bootstrap process.  Sometimes things can go wrong with CRAN / R version differences.  I won't be able to troubleshoot for another week or two, but perhaps @hdoubleu has some insight here.

**Comment by bhawani14** [comment]
Actually it was silly of me...

I simply had to load the packages from the R console..


Many thanks...

Bhawani
