### ISSUE TITLE
AMI Version error while executing tessera-emr.sh

### ISSUE THREAD

**Issue by aglsharad** [tesseradata/install-emr#18]
I am running tessera-emr.sh to create the cluster on AWS. While running the script, I am getting below error. What could be the reason?

An error occurred (ValidationException) when calling the RunJobFlow operation: AMI version 3.11.0 is not supported.

Thanks.

**Comment by hafen** [comment]
Interesting.  I just re-tried the script and verified that it works for me.  These things can be tricky because there are so many variables and unknowns.  What region are you running from?

**Comment by aglsharad** [comment]
Thanks. I was using ap-south-1.
It however worked for region us-west-1
