### ISSUE TITLE
Error installing R on m3.2xlarge instance

### ISSUE THREAD

**Issue by saptarshiguha** [tesseradata/install-emr#5]
Hello,

I got this error

gpg: directory `/home/hadoop/.gnupg' created
gpg: new configuration file `/home/hadoop/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/hadoop/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/hadoop/.gnupg/secring.gpg' created
gpg: keyring `/home/hadoop/.gnupg/pubring.gpg' created
gpg: requesting key 381BA480 from hkp server pgpkeys.mit.edu
gpg: /home/hadoop/.gnupg/trustdb.gpg: trustdb created
gpg: key 381BA480: public key "Johannes Ranke (CRAN Debian archive) <jranke@uni-bremen.de>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
E: Version '3.1.0-1~squeezecran3.0' for 'r-base-core' was not found
E: Version '3.1.0-1~squeezecran3.0' for 'r-base-dev' was not found
chmod: cannot access `/usr/local/lib/R/site-library': No such file or directory

This from the script given by https://github.com/saptarshiguha/install-emr/blob/master/emr-2.4.2/install-r

(which is similar to that given in the main repo)

**Comment by hafen** [comment]
emr-2 is deprecated so I'm closing this.
